import type { Practice } from "./types"

export const mockPractices: Practice[] = [
  {
    place_id: "mock_dental_houston_001",
    name: "Bright Smile Dental",
    address: "1200 Main St, Houston, TX 77002",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-0101",
    website: "https://brightsmiledental.example.com",
    rating: 4.7,
    review_count: 312,
    category: "dental",
    lat: 29.7604,
    lng: -95.3698,
    opening_hours: "Mon-Fri 8am-6pm, Sat 9am-2pm",
    status: "NEW",
  },
  {
    place_id: "mock_dental_houston_002",
    name: "Midtown Family Dentistry",
    address: "3400 Montrose Blvd, Houston, TX 77006",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-0102",
    website: "https://midtownfamilydentistry.example.com",
    rating: 4.5,
    review_count: 189,
    category: "dental",
    lat: 29.7419,
    lng: -95.3908,
    opening_hours: "Mon-Fri 9am-5pm",
    status: "NEW",
  },
  {
    place_id: "mock_dental_houston_003",
    name: "Heights Dental Studio",
    address: "802 Yale St, Houston, TX 77007",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-0103",
    website: "https://heightsdentalstudio.example.com",
    rating: 4.9,
    review_count: 445,
    category: "dental",
    lat: 29.7908,
    lng: -95.3987,
    opening_hours: "Mon-Thu 8am-7pm, Fri 8am-3pm",
    status: "NEW",
  },
  {
    place_id: "mock_dental_dallas_001",
    name: "Uptown Dental Arts",
    address: "4514 Travis St, Dallas, TX 75205",
    city: "Dallas",
    state: "TX",
    phone: "(214) 555-0201",
    website: "https://uptowndentalarts.example.com",
    rating: 4.3,
    review_count: 156,
    category: "dental",
    lat: 32.8096,
    lng: -96.7969,
    opening_hours: "Mon-Fri 8am-5pm, Sat 9am-1pm",
    status: "NEW",
  },
  {
    place_id: "mock_dental_miami_001",
    name: "Brickell Dental Care",
    address: "1001 Brickell Bay Dr, Miami, FL 33131",
    city: "Miami",
    state: "FL",
    phone: "(305) 555-0301",
    website: "https://brickelldentalcare.example.com",
    rating: 4.4,
    review_count: 203,
    category: "dental",
    lat: 25.7617,
    lng: -80.1893,
    opening_hours: "Mon-Fri 8am-6pm, Sat 9am-3pm",
    status: "NEW",
  },
  {
    place_id: "mock_dental_la_001",
    name: "Beverly Hills Premier Dental",
    address: "9615 Brighton Way, Beverly Hills, CA 90210",
    city: "Los Angeles",
    state: "CA",
    phone: "(310) 555-0401",
    website: "https://bhpremierdental.example.com",
    rating: 4.8,
    review_count: 523,
    category: "dental",
    lat: 34.0674,
    lng: -118.4003,
    opening_hours: "Mon-Fri 8am-6pm",
    status: "NEW",
  },
  {
    place_id: "mock_dental_ny_001",
    name: "Manhattan Dental Loft",
    address: "225 Broadway, New York, NY 10007",
    city: "New York",
    state: "NY",
    phone: "(212) 555-0501",
    website: "https://manhattandentalloft.example.com",
    rating: 4.2,
    review_count: 176,
    category: "dental",
    lat: 40.7128,
    lng: -74.006,
    opening_hours: "Mon-Fri 7am-7pm",
    status: "NEW",
  },
  {
    place_id: "mock_chiro_houston_001",
    name: "Galleria Chiropractic & Wellness",
    address: "5085 Westheimer Rd, Houston, TX 77056",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-0601",
    website: "https://galleriachiro.example.com",
    rating: 4.6,
    review_count: 287,
    category: "chiropractic",
    lat: 29.739,
    lng: -95.4605,
    opening_hours: "Mon-Fri 8am-6pm, Sat 9am-12pm",
    status: "NEW",
  },
  {
    place_id: "mock_chiro_austin_001",
    name: "South Lamar Chiropractic",
    address: "3005 S Lamar Blvd, Austin, TX 78704",
    city: "Austin",
    state: "TX",
    phone: "(512) 555-0701",
    website: "https://southlamarchiro.example.com",
    rating: 4.4,
    review_count: 178,
    category: "chiropractic",
    lat: 30.2427,
    lng: -97.7734,
    opening_hours: "Mon-Fri 9am-6pm",
    status: "NEW",
  },
  {
    place_id: "mock_chiro_sandiego_001",
    name: "Pacific Beach Chiropractic",
    address: "1688 Garnet Ave, San Diego, CA 92109",
    city: "San Diego",
    state: "CA",
    phone: "(858) 555-0901",
    website: "https://pbchiro.example.com",
    rating: 4.7,
    review_count: 345,
    category: "chiropractic",
    lat: 32.7979,
    lng: -117.2408,
    opening_hours: "Mon-Fri 7am-6pm, Sat 8am-12pm",
    status: "NEW",
  },
  {
    place_id: "mock_urgent_houston_001",
    name: "CityMed Urgent Care",
    address: "5510 Kirby Dr, Houston, TX 77005",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-1101",
    website: "https://citymedurgent.example.com",
    rating: 4.0,
    review_count: 456,
    category: "urgent_care",
    lat: 29.7216,
    lng: -95.4148,
    opening_hours: "Daily 8am-10pm",
    status: "NEW",
  },
  {
    place_id: "mock_urgent_orlando_001",
    name: "Lake Eola Walk-In Clinic",
    address: "200 E Robinson St, Orlando, FL 32801",
    city: "Orlando",
    state: "FL",
    phone: "(407) 555-1301",
    website: "https://lakeolawalkin.example.com",
    rating: 4.1,
    review_count: 234,
    category: "urgent_care",
    lat: 28.542,
    lng: -81.3687,
    opening_hours: "Daily 8am-10pm",
    status: "NEW",
  },
  {
    place_id: "mock_urgent_sf_001",
    name: "SOMA QuickCare",
    address: "888 Brannan St, San Francisco, CA 94103",
    city: "San Francisco",
    state: "CA",
    phone: "(415) 555-1401",
    website: "https://somaquickcare.example.com",
    rating: 4.3,
    review_count: 278,
    category: "urgent_care",
    lat: 37.7715,
    lng: -122.4036,
    opening_hours: "Daily 7am-10pm",
    status: "NEW",
  },
  {
    place_id: "mock_psych_houston_001",
    name: "Houston Mind & Wellness Center",
    address: "6550 Fannin St, Houston, TX 77030",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-1601",
    website: "https://houstonmindwellness.example.com",
    rating: 4.6,
    review_count: 189,
    category: "mental_health",
    lat: 29.7101,
    lng: -95.3984,
    opening_hours: "Mon-Fri 8am-7pm",
    status: "NEW",
  },
  {
    place_id: "mock_psych_la_001",
    name: "West Hollywood Behavioral Health",
    address: "8730 Sunset Blvd, West Hollywood, CA 90069",
    city: "Los Angeles",
    state: "CA",
    phone: "(310) 555-1801",
    website: "https://wehobehavioral.example.com",
    rating: 4.7,
    review_count: 267,
    category: "mental_health",
    lat: 34.0903,
    lng: -118.3822,
    opening_hours: "Mon-Fri 8am-8pm, Sat 9am-2pm",
    status: "NEW",
  },
  {
    place_id: "mock_primary_houston_001",
    name: "Montrose Family Medicine",
    address: "1415 California St, Houston, TX 77006",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-2101",
    website: "https://montrosefamilymed.example.com",
    rating: 4.5,
    review_count: 334,
    category: "primary_care",
    lat: 29.7434,
    lng: -95.3938,
    opening_hours: "Mon-Fri 7am-5pm",
    status: "NEW",
  },
  {
    place_id: "mock_primary_columbus_001",
    name: "German Village Family Practice",
    address: "625 S 3rd St, Columbus, OH 43206",
    city: "Columbus",
    state: "OH",
    phone: "(614) 555-2401",
    website: "https://germanvillagefp.example.com",
    rating: 4.4,
    review_count: 212,
    category: "primary_care",
    lat: 39.9491,
    lng: -82.9852,
    opening_hours: "Mon-Fri 7:30am-5pm",
    status: "NEW",
  },
  {
    place_id: "mock_specialty_houston_001",
    name: "Texas Medical Center Orthopedics",
    address: "7200 Cambridge St, Houston, TX 77030",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-2601",
    website: "https://tmcortho.example.com",
    rating: 4.8,
    review_count: 567,
    category: "specialty",
    lat: 29.7063,
    lng: -95.4009,
    opening_hours: "Mon-Fri 8am-5pm",
    status: "NEW",
  },
  {
    place_id: "mock_specialty_ny_001",
    name: "Midtown Gastroenterology",
    address: "635 Madison Ave, New York, NY 10022",
    city: "New York",
    state: "NY",
    phone: "(212) 555-3001",
    website: "https://midtowngastro.example.com",
    rating: 4.4,
    review_count: 234,
    category: "specialty",
    lat: 40.7627,
    lng: -73.9718,
    opening_hours: "Mon-Fri 8am-6pm",
    status: "NEW",
  },
  {
    place_id: "mock_specialty_la_001",
    name: "Cedars-Adjacent ENT Specialists",
    address: "100 N La Cienega Blvd, Los Angeles, CA 90048",
    city: "Los Angeles",
    state: "CA",
    phone: "(323) 555-2901",
    website: "https://cedarsent.example.com",
    rating: 4.3,
    review_count: 178,
    category: "specialty",
    lat: 34.0736,
    lng: -118.3776,
    opening_hours: "Mon-Fri 9am-5pm",
    status: "NEW",
  },
]
