import type { Practice } from "./types"

export const mockPractices: Practice[] = [
  {
    place_id: "real_dental_houston_001",
    name: "Houston Dental Care",
    address: "5765 Westheimer Rd, Houston, TX 77057",
    city: "Houston",
    state: "TX",
    phone: "(713) 956-0833",
    website: "https://www.houstondentalcare.org/",
    rating: 4.6,
    review_count: 285,
    category: "dental",
    lat: 29.7372,
    lng: -95.4745,
    opening_hours: "Mon-Fri 8am-5pm, Sat 9am-2pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_dental_houston_002",
    name: "Fresh Dental Care",
    address: "6550 Mapleridge St, Houston, TX 77081",
    city: "Houston",
    state: "TX",
    phone: "(713) 729-6100",
    website: "https://www.freshdentalcare.com/",
    rating: 4.5,
    review_count: 192,
    category: "dental",
    lat: 29.7235,
    lng: -95.4753,
    opening_hours: "Mon-Fri 9am-6pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_dental_houston_003",
    name: "UT Dentists",
    address: "7500 Cambridge St, Houston, TX 77054",
    city: "Houston",
    state: "TX",
    phone: "(713) 486-4000",
    website: "https://www.utdentists.com/",
    rating: 4.2,
    review_count: 520,
    category: "dental",
    lat: 29.7063,
    lng: -95.4009,
    opening_hours: "Mon-Fri 8am-5pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_dental_houston_004",
    name: "EZ Dental Clinic",
    address: "6918 Wilcrest Dr, Houston, TX 77072",
    city: "Houston",
    state: "TX",
    phone: "(281) 530-0700",
    website: "https://ezdentalclinic.com/",
    rating: 4.4,
    review_count: 167,
    category: "dental",
    lat: 29.7109,
    lng: -95.5612,
    opening_hours: "Mon-Sat 9am-6pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_chiro_austin_001",
    name: "Wellness for Austin",
    address: "8701 Shoal Creek Blvd, Austin, TX 78757",
    city: "Austin",
    state: "TX",
    phone: "(512) 372-8898",
    website: "https://www.wellnessforaustin.com/",
    rating: 4.8,
    review_count: 234,
    category: "chiropractic",
    lat: 30.3544,
    lng: -97.7401,
    opening_hours: "Mon-Fri 8am-6pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_chiro_austin_002",
    name: "Austin Chiropractic & Rehab",
    address: "8711 Burnet Rd, Austin, TX 78757",
    city: "Austin",
    state: "TX",
    phone: "(512) 451-0115",
    website: "https://www.austinchiroandrehab.com/",
    rating: 4.5,
    review_count: 178,
    category: "chiropractic",
    lat: 30.3548,
    lng: -97.7418,
    opening_hours: "Mon-Fri 9am-6pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_chiro_austin_003",
    name: "Discover Chiropractic Austin",
    address: "4201 S Congress Ave, Austin, TX 78745",
    city: "Austin",
    state: "TX",
    phone: "(512) 444-2727",
    website: "https://www.discoverchiropracticaustin.com/",
    rating: 4.9,
    review_count: 412,
    category: "chiropractic",
    lat: 30.2253,
    lng: -97.7630,
    opening_hours: "Mon-Thu 8am-6pm, Fri 8am-12pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_urgent_dallas_001",
    name: "CityDoc Urgent Care Uptown",
    address: "3535 Travis St, Dallas, TX 75204",
    city: "Dallas",
    state: "TX",
    phone: "(214) 871-7000",
    website: "https://citydoc.net/",
    rating: 4.3,
    review_count: 356,
    category: "urgent_care",
    lat: 32.8096,
    lng: -96.7969,
    opening_hours: "Mon-Sun 8am-8pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_urgent_dallas_002",
    name: "Citra Urgent Care",
    address: "5680 Forest Ln, Dallas, TX 75230",
    city: "Dallas",
    state: "TX",
    phone: "(469) 731-2500",
    website: "https://citracare.com/",
    rating: 4.5,
    review_count: 423,
    category: "urgent_care",
    lat: 32.9001,
    lng: -96.7834,
    opening_hours: "Mon-Sun 8am-9pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_urgent_dallas_003",
    name: "Integra Urgent Care",
    address: "2780 N Stemmons Fwy, Dallas, TX 75207",
    city: "Dallas",
    state: "TX",
    phone: "(972) 850-9950",
    website: "https://integrauc.com/",
    rating: 4.2,
    review_count: 198,
    category: "urgent_care",
    lat: 32.8013,
    lng: -96.8254,
    opening_hours: "Mon-Sun 9am-9pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_mental_miami_001",
    name: "AMP Mental Health",
    address: "175 SW 7th St, Miami, FL 33130",
    city: "Miami",
    state: "FL",
    phone: "(305) 999-8226",
    website: "https://ampmentalhealth.com/",
    rating: 4.7,
    review_count: 189,
    category: "mental_health",
    lat: 25.7669,
    lng: -80.1996,
    opening_hours: "Mon-Fri 9am-6pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_mental_miami_002",
    name: "Miami Mental Health & Wellness",
    address: "1001 Brickell Bay Dr, Miami, FL 33131",
    city: "Miami",
    state: "FL",
    phone: "(786) 780-8443",
    website: "https://miamimentalhw.com/",
    rating: 4.5,
    review_count: 145,
    category: "mental_health",
    lat: 25.7617,
    lng: -80.1893,
    opening_hours: "Mon-Fri 8am-7pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_primary_columbus_001",
    name: "Complete Healthcare Columbus",
    address: "5965 E Broad St, Columbus, OH 43213",
    city: "Columbus",
    state: "OH",
    phone: "(614) 751-9990",
    website: "https://completehealthcare.com/",
    rating: 4.3,
    review_count: 212,
    category: "primary_care",
    lat: 39.9828,
    lng: -82.8185,
    opening_hours: "Mon-Fri 8am-5pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
  {
    place_id: "real_primary_columbus_002",
    name: "Living Hope Primary Care",
    address: "3600 Olentangy River Rd, Columbus, OH 43214",
    city: "Columbus",
    state: "OH",
    phone: "(614) 456-7890",
    website: "https://www.livinghopeprimarycare.com/",
    rating: 4.6,
    review_count: 178,
    category: "primary_care",
    lat: 40.0342,
    lng: -83.0221,
    opening_hours: "Mon-Fri 7:30am-5pm",
    status: "NEW",
    email: null,
    email_draft: null,
    email_draft_updated_at: null,
    last_touched_by: null,
    last_touched_by_name: null,
    last_touched_at: null,
    salesforce_lead_id: null,
    salesforce_owner_id: null,
    salesforce_owner_name: null,
    salesforce_synced_at: null,
    call_count: 0,
    call_notes: null,
  },
]
